fix intermittency in GatewayPublicationTest
GatewayPublicationTest > testSavingMessagesOverTermBoundary(int) > [11] 1315 FAILED
    org.opentest4j.AssertionFailedError: failed to save message: -2
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
        at app//org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
        at app//uk.co.real_logic.artio.protocol.GatewayPublicationTest.testSavingMessagesOverTermBoundary(GatewayPublicationTest.java:98)

(cherry picked from commit d138075d873506c7453f6215529475e7a3ce11b5)